### ISSUE TITLE
Revert registry changes

### ISSUE THREAD

**Issue by hexfactor** [x2es/bt-dualboot#21]
I've run the program to sync one device (with the backup flag enabled) between Fedora Linux and Windows 11, but now Bluetooth isn't working at all on my Windows installation. None of the Bluetooth devices I've tried to connect to have been able to connect. 

I have since "forgotten" the device through Windows settings, removed it through `bluetoothctl` on Linux and factory reset the Bluetooth device itself, but still cannot connect to it nor any other Bluetooth device. 

Is there some way I can restore my registry using the generated backup or revert the changes done?

**Comment by russjr08** [comment]
*Obligatory proceed with caution and other standard disclaimers - I'm not the dev*

I've not tried this myself, but based off what I can see in [windows_registry.py](https://github.com/x2es/bt-dualboot/blob/master/bt_dualboot/windows_registry/windows_registry.py#L9) the specific file that bt-dualboot modifies is under `\Windows\System32\config` called `SYSTEM`. bt-dualboot just copies that file over to `/var/backup/bt-dualboot` (by default, unless you passed in a specific path).

So theoretically, as far as I can tell, you should just be able to do the reverse and copy that file back over to your Windows partition in the mentioned directory. Of course, be sure that after you do so, you cleanly unmount the partition (to flush any writes that are pending). It's also probably worth disabling Windows' Fast Boot feature if you haven't already, before doing this as well.

**Comment by hexfactor** [comment]
Thanks @russjr08. Looking at the file you mentioned, that seems to be the right way to do it. 

(I didn't get the chance to try it because I'd already decided to load a Windows system backup instead, but thanks for the help anyway.)
